<?php

/*
 * Copyright(c) 2020 Shadow Enterprise, Inc. All rights reserved.
 * http://www.shadow-ep.co.jp/
 */

namespace Plugin\SeEnquete4\Repository;

use Eccube\Repository\AbstractRepository;
use Plugin\SeEnquete4\Entity\EnqueteConfig;
use Symfony\Bridge\Doctrine\RegistryInterface;
use Symfony\Component\HttpKernel\KernelInterface;

/**
 * EnqueteConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnqueteConfigRepository extends AbstractRepository
{
    /**
     * EnqueteConfigRepository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, EnqueteConfig::class);
    }

    /**
     * @param int $id
     * @return null|EnqueteConfig
     */
    public function get($id = 1)
    {
        return $this->find($id);
    }
}
